FROM ruby:3.4.6-slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libyaml-dev \
      pkg-config \
      libsqlite3-dev \
      curl \
      nodejs \
      npm \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /rails

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

CMD ["bin/dev"]